on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  getVersion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Get version from Chart.yaml
        id: get_version
        run: |
          VERSION=$(yq -r ".version" helpers/Chart.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  tag-and-release:
    needs: getVersion
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ needs.getVersion.outputs.version }}

    steps:
      - name: Create tag
        run: |
          git tag $VERSION && git push --tags

  publish:
    needs: getVersion
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install helm
        uses: azure/setup-helm@v4.3.0

      - name: Package Helm Chart
        run: |
          cd helpers
          helm package .

      - name: Log in into Helm
        run: |
          helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Helm
        run: |
          helm push *.tgz oci://$IMAGE_NAME
