on:
  push:
    branches: ["main"]

jobs:
  getVersion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Get version from Chart.yaml
        id: get_version
        run: |
          VERSION=$(yq -r ".version" helpers/Chart.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  tag-and-release:
    needs: getVersion
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      VERSION: ${{ needs.getVersion.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create tag
        run: |
          git tag $VERSION && git push --tags

  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    env:
      REGISTRY: ghcr.io
      REPO_OWNER: ${{ github.repository_owner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install helm
        uses: azure/setup-helm@v4.3.0

      - name: Package Helm Chart
        run: |
          cd helpers
          helm package .
          echo "PKG=$(ls *.tgz | tail -n 1)" >> $GITHUB_ENV

      - name: Log in into Helm
        run: |
          helm registry login $REGISTRY -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Helm
        run: |
          cd helpers
          helm push $PKG oci://$REGISTRY/${REPO_OWNER,,}
